=== Smitaty/FrameworkAnimationJS/VersionJS/animation.dtd
<?xml version="1.0" encoding="utf-8" ?>

<!ELEMENT animation (init?,background?,objects,programs) >

<!ELEMENT init (start_button) >
<!ELEMENT start_button EMPTY >
<!ATTLIST start_button text CDATA #IMPLIED >
<!ATTLIST start_button x CDATA #IMPLIED >
<!ATTLIST start_button y CDATA #IMPLIED >
<!ATTLIST start_button present (true|false) #IMPLIED >

<!ELEMENT background (#PCDATA) >

<!ELEMENT objects (object_text|object_image|object_rectangle|object_polygon|object_circle|object_ellipse|object_extern)+ >

<!ELEMENT object_text (#PCDATA) >
<!ATTLIST object_text text CDATA #REQUIRED >
<!ATTLIST object_text font CDATA #REQUIRED >
<!ATTLIST object_text fgcolor CDATA #IMPLIED >
<!ATTLIST object_text bgcolor CDATA #IMPLIED >
<!ATTLIST object_text bocolor CDATA #IMPLIED >
<!ATTLIST object_text border CDATA #IMPLIED >
<!ATTLIST object_text transparency (true|false) #IMPLIED >
<!ATTLIST object_text layer CDATA #IMPLIED >

<!ELEMENT object_image (#PCDATA) >
<!ATTLIST object_image image CDATA #REQUIRED >
<!ATTLIST object_image fgcolor CDATA #IMPLIED >
<!ATTLIST object_image bgcolor CDATA #IMPLIED >
<!ATTLIST object_image layer CDATA #IMPLIED >
<!ATTLIST object_image width CDATA #IMPLIED >
<!ATTLIST object_image height CDATA #IMPLIED >

<!ELEMENT object_rectangle (#PCDATA) >
<!ATTLIST object_rectangle width CDATA #REQUIRED >
<!ATTLIST object_rectangle height CDATA #REQUIRED >
<!ATTLIST object_rectangle fgcolor CDATA #IMPLIED >
<!ATTLIST object_rectangle bgcolor CDATA #IMPLIED >
<!ATTLIST object_rectangle bocolor CDATA #IMPLIED >
<!ATTLIST object_rectangle layer CDATA #IMPLIED >

<!ELEMENT object_polygon (#PCDATA) >
<!ATTLIST object_polygon coord_x CDATA #REQUIRED >
<!ATTLIST object_polygon coord_y CDATA #REQUIRED >
<!ATTLIST object_polygon fgcolor CDATA #IMPLIED >
<!ATTLIST object_polygon bgcolor CDATA #IMPLIED >
<!ATTLIST object_polygon bocolor CDATA #IMPLIED >
<!ATTLIST object_polygon layer CDATA #IMPLIED >

<!ELEMENT object_cicle (#PCDATA) >
<!ATTLIST object_circle rayon CDATA #REQUIRED >
<!ATTLIST object_circle fgcolor CDATA #IMPLIED >
<!ATTLIST object_circle bgcolor CDATA #IMPLIED >
<!ATTLIST object_circle layer CDATA #IMPLIED >

<!ELEMENT object_ellipse (#PCDATA) >
<!ATTLIST object_ellipse width CDATA #REQUIRED >
<!ATTLIST object_ellipse height CDATA #REQUIRED >
<!ATTLIST object_ellipse fgcolor CDATA #IMPLIED >
<!ATTLIST object_ellipse bgcolor CDATA #IMPLIED >
<!ATTLIST object_ellipse layer CDATA #IMPLIED >
<!ATTLIST object_ellipse transparency (true|false) #IMPLIED >

<!ELEMENT object_extern (#PCDATA) >
<!ATTLIST object_extern class CDATA #REQUIRED >
<!ATTLIST object_extern constructor CDATA #REQUIRED >

<!ELEMENT programs (program+) >

<!ELEMENT program (visible|label|setxy|setx|sety|moveto|wait|sleep|state|goto|trigger|up|down|left|right|angle|click|setproperty|blink|stop)+ >
<!ATTLIST program assigned_to CDATA #REQUIRED >

<!ELEMENT click EMPTY >

<!ELEMENT visible EMPTY >
<!ATTLIST visible value CDATA #REQUIRED >

<!ELEMENT label EMPTY >
<!ATTLIST label value CDATA #REQUIRED >

<!ELEMENT setxy EMPTY >
<!ATTLIST setxy x CDATA #REQUIRED >
<!ATTLIST setxy y CDATA #REQUIRED >

<!ELEMENT setx EMPTY >
<!ATTLIST setx x CDATA #REQUIRED >

<!ELEMENT sety EMPTY >
<!ATTLIST sety y CDATA #REQUIRED >

<!ELEMENT moveto EMPTY >
<!ATTLIST moveto x CDATA #REQUIRED >
<!ATTLIST moveto y CDATA #REQUIRED >
<!ATTLIST moveto dx CDATA #REQUIRED >
<!ATTLIST moveto dy CDATA #REQUIRED >
<!ATTLIST moveto delay CDATA #REQUIRED >

<!ELEMENT wait EMPTY >
<!ATTLIST wait value CDATA #REQUIRED >

<!ELEMENT sleep EMPTY >
<!ATTLIST sleep value CDATA #REQUIRED >

<!ELEMENT state EMPTY >
<!ATTLIST state value CDATA #REQUIRED >

<!ELEMENT trigger EMPTY >
<!ATTLIST trigger object CDATA #REQUIRED >
<!ATTLIST trigger value CDATA #REQUIRED >

<!ELEMENT goto EMPTY >
<!ATTLIST goto value CDATA #REQUIRED >

<!ELEMENT up EMPTY >
<!ATTLIST up y CDATA #REQUIRED >
<!ATTLIST up dy CDATA #REQUIRED >

<!ELEMENT down EMPTY >
<!ATTLIST down y CDATA #REQUIRED >
<!ATTLIST down dy CDATA #REQUIRED >

<!ELEMENT left EMPTY >
<!ATTLIST left x CDATA #REQUIRED >
<!ATTLIST left dx CDATA #REQUIRED >

<!ELEMENT right EMPTY >
<!ATTLIST right x CDATA #REQUIRED >
<!ATTLIST right dx CDATA #REQUIRED >

<!ELEMENT angle EMPTY >
<!ATTLIST angle degrees CDATA #REQUIRED >

<!ELEMENT setproperty EMPTY >
<!ATTLIST setproperty object CDATA #REQUIRED >
<!ATTLIST setproperty property CDATA #REQUIRED >
<!ATTLIST setproperty value CDATA #REQUIRED >

<!ELEMENT blink EMPTY >
<!ATTLIST blink times CDATA #REQUIRED >
<!ATTLIST blink delay CDATA #REQUIRED >

<!ELEMENT stop EMPTY >

=== Smitaty/FrameworkAnimationJS/cpu_dual_core.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animation SYSTEM "animation.dtd">
<animation>
  <init>
    <start_button present="false" />
  </init>

  <background>VersionJS/img/cpu_dual_core.png</background>

  <objects>
    <object_text
      text="Press on i1 to start"
      font="Courier,12,bold"
      color="0,0,0"
      border="2"
      bgtransparent="true">Message</object_text>

    <object_text
      text="i1"
      font="Courier,12,bold"
      bgcolor="255,127,0"
      color="0,0,0"
      border="2"
      bgtransparent="false">I1</object_text>

    <object_text
      text="i2"
      font="Courier,12,bold"
      bgcolor="255,127,0"
      color="0,0,0"
      border="2"
      bgtransparent="false">I2</object_text>

    <object_text
      text="i3"
      font="Courier,12,bold"
      bgcolor="255,127,0"
      color="0,0,0"
      border="2"
      bgtransparent="false">I3</object_text>

    <object_text
      text="i4"
      font="Courier,12,bold"
      bgcolor="255,127,0"
      color="0,0,0"
      border="2"
      bgtransparent="false">I4</object_text>

    <object_text
      text="j1"
      font="Courier,12,bold"
      bgcolor="0,102,204"
      color="255,255,255"
      border="2"
      bgtransparent="false">J1</object_text>

    <object_text
      text="j2"
      font="Courier,12,bold"
      bgcolor="0,102,204"
      color="255,255,255"
      border="2"
      bgtransparent="false">J2</object_text>

    <object_text
      text="j3"
      font="Courier,12,bold"
      bgcolor="0,102,204"
      color="255,255,255"
      border="2"
      bgtransparent="false">J3</object_text>

    <object_text
      text="j4"
      font="Courier,12,bold"
      bgcolor="0,102,204"
      color="255,255,255"
      border="2"
      bgtransparent="false">J4</object_text>

    <object_text
      text="i1"
      font="Courier,12,bold"
      bgcolor="255,127,0"
      color="0,0,0"
      border="2"
      bgtransparent="false">I1D</object_text>

    <object_text
      text="i2"
      font="Courier,12,bold"
      bgcolor="255,127,0"
      color="0,0,0"
      border="2"
      bgtransparent="false">I2D</object_text>

    <object_text
      text="i3"
      font="Courier,12,bold"
      bgcolor="255,127,0"
      color="0,0,0"
      border="2"
      bgtransparent="false">I3D</object_text>

    <object_text
      text="i4"
      font="Courier,12,bold"
      bgcolor="255,127,0"
      color="0,0,0"
      border="2"
      bgtransparent="false">I4D</object_text>

    <object_text
      text="j1"
      font="Courier,12,bold"
      bgcolor="0,102,204"
      color="255,255,255"
      border="2"
      bgtransparent="false">J1D</object_text>

    <object_text
      text="j2"
      font="Courier,12,bold"
      bgcolor="0,102,204"
      color="255,255,255"
      border="2"
      bgtransparent="false">J2D</object_text>

    <object_text
      text="j3"
      font="Courier,12,bold"
      bgcolor="0,102,204"
      color="255,255,255"
      border="2"
      bgtransparent="false">J3D</object_text>

    <object_text
      text="j4"
      font="Courier,12,bold"
      bgcolor="0,102,204"
      color="255,255,255"
      border="2"
      bgtransparent="false">J4D</object_text>

  </objects>

  <programs>

    <program assigned_to="Message">
      <setxy x="20" y="20" />
      <visible value="true" />
      <wait value="i1_clicked" />
      <visible value="false" />
    </program>

    <program assigned_to="I1">
      <setxy x="100" y="77" />
      <visible value="true" />
      <click />
      <trigger object="Message" value="i1_clicked" />
      <trigger object="I1D" value="unlock" />
      <right x="135" dx="5" />
      <down y="40" dy="1" />
      <trigger object="J1" value="unlock" />
      <right x="375" dx="2" />
    </program>

    <program assigned_to="I2">
      <setxy x="75" y="77" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="160" dx="5" />
      <down y="40" dy="1" />
      <trigger object="J2" value="unlock" />
      <right x="325" dx="2" />
    </program>

    <program assigned_to="I3">
      <setxy x="50" y="77" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="185" dx="5" />
      <down y="40" dy="1" />
      <trigger object="J3" value="unlock" />
      <right x="275" dx="2" />
    </program>

    <program assigned_to="I4">
      <setxy x="25" y="77" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="210" dx="5" />
      <down y="40" dy="1" />
      <trigger object="J4" value="unlock" />
      <right x="225" dx="2" />
    </program>

    <program assigned_to="J1">
      <setxy x="100" y="157" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="135" dx="5" />
      <up y="40" dy="1" />
      <trigger object="I2" value="unlock" />
      <right x="350" dx="2" />
    </program>

    <program assigned_to="J2">
      <setxy x="75" y="157" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="160" dx="5" />
      <up y="40" dy="1" />
      <trigger object="I3" value="unlock" />
      <right x="300" dx="2" />
    </program>

    <program assigned_to="J3">
      <setxy x="50" y="157" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="185" dx="5" />
      <up y="40" dy="1" />
      <trigger object="I4" value="unlock" />
      <right x="250" dx="2" />
    </program>

    <program assigned_to="J4">
      <setxy x="25" y="157" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="210" dx="5" />
      <up y="40" dy="1" />
      <right x="200" dx="2" />
    </program>

    <program assigned_to="I1D">
      <setxy x="100" y="277" />
      <visible value="true" />
      <wait value="unlock" />
      <trigger object="J1D" value="unlock" />
      <right x="135" dx="4" />
      <down y="30" dy="1" />
      <trigger object="I2D" value="unlock" />
      <right x="375" dx="2" />
    </program>

    <program assigned_to="I2D">
      <setxy x="75" y="277" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="160" dx="5" />
      <down y="30" dy="1" />
      <trigger object="I3D" value="unlock" />
      <right x="350" dx="2" />
    </program>

    <program assigned_to="I3D">
      <setxy x="50" y="277" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="185" dx="5" />
      <down y="30" dy="1" />
      <trigger object="I4D" value="unlock" />
      <right x="325" dx="2" />
    </program>

    <program assigned_to="I4D">
      <setxy x="25" y="277" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="210" dx="5" />
      <down y="30" dy="1" />
      <right x="300" dx="2" />
    </program>

    <program assigned_to="J1D">
      <setxy x="100" y="357" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="135" dx="4" />
      <up y="30" dy="1" />
      <trigger object="J2D" value="unlock" />
      <right x="375" dx="2" />
    </program>

    <program assigned_to="J2D">
      <setxy x="75" y="357" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="160" dx="5" />
      <up y="30" dy="1" />
      <trigger object="J3D" value="unlock" />
      <right x="350" dx="2" />
    </program>

    <program assigned_to="J3D">
      <setxy x="50" y="357" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="185" dx="5" />
      <up y="30" dy="1" />
      <trigger object="J4D" value="unlock" />
      <right x="325" dx="2" />
    </program>

    <program assigned_to="J4D">
      <setxy x="25" y="357" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="210" dx="5" />
      <up y="30" dy="1" />
      <right x="300" dx="2" />
    </program>

  </programs>

</animation>
