=== Smitaty/FrameworkAnimationJS/VersionJS/animation.dtd
<?xml version="1.0" encoding="utf-8" ?>

<!ELEMENT animation (init?,background?,objects,programs) >

<!ELEMENT init (start_button) >
<!ELEMENT start_button EMPTY >
<!ATTLIST start_button text CDATA #IMPLIED >
<!ATTLIST start_button x CDATA #IMPLIED >
<!ATTLIST start_button y CDATA #IMPLIED >
<!ATTLIST start_button present (true|false) #IMPLIED >

<!ELEMENT background (#PCDATA) >

<!ELEMENT objects (object_text|object_image|object_rectangle|object_polygon|object_circle|object_ellipse|object_extern)+ >

<!ELEMENT object_text (#PCDATA) >
<!ATTLIST object_text text CDATA #REQUIRED >
<!ATTLIST object_text font CDATA #REQUIRED >
<!ATTLIST object_text fgcolor CDATA #IMPLIED >
<!ATTLIST object_text bgcolor CDATA #IMPLIED >
<!ATTLIST object_text bocolor CDATA #IMPLIED >
<!ATTLIST object_text border CDATA #IMPLIED >
<!ATTLIST object_text transparency (true|false) #IMPLIED >
<!ATTLIST object_text layer CDATA #IMPLIED >

<!ELEMENT object_image (#PCDATA) >
<!ATTLIST object_image image CDATA #REQUIRED >
<!ATTLIST object_image fgcolor CDATA #IMPLIED >
<!ATTLIST object_image bgcolor CDATA #IMPLIED >
<!ATTLIST object_image layer CDATA #IMPLIED >
<!ATTLIST object_image width CDATA #IMPLIED >
<!ATTLIST object_image height CDATA #IMPLIED >

<!ELEMENT object_rectangle (#PCDATA) >
<!ATTLIST object_rectangle width CDATA #REQUIRED >
<!ATTLIST object_rectangle height CDATA #REQUIRED >
<!ATTLIST object_rectangle fgcolor CDATA #IMPLIED >
<!ATTLIST object_rectangle bgcolor CDATA #IMPLIED >
<!ATTLIST object_rectangle bocolor CDATA #IMPLIED >
<!ATTLIST object_rectangle layer CDATA #IMPLIED >

<!ELEMENT object_polygon (#PCDATA) >
<!ATTLIST object_polygon coord_x CDATA #REQUIRED >
<!ATTLIST object_polygon coord_y CDATA #REQUIRED >
<!ATTLIST object_polygon fgcolor CDATA #IMPLIED >
<!ATTLIST object_polygon bgcolor CDATA #IMPLIED >
<!ATTLIST object_polygon bocolor CDATA #IMPLIED >
<!ATTLIST object_polygon layer CDATA #IMPLIED >

<!ELEMENT object_cicle (#PCDATA) >
<!ATTLIST object_circle rayon CDATA #REQUIRED >
<!ATTLIST object_circle fgcolor CDATA #IMPLIED >
<!ATTLIST object_circle bgcolor CDATA #IMPLIED >
<!ATTLIST object_circle layer CDATA #IMPLIED >

<!ELEMENT object_ellipse (#PCDATA) >
<!ATTLIST object_ellipse width CDATA #REQUIRED >
<!ATTLIST object_ellipse height CDATA #REQUIRED >
<!ATTLIST object_ellipse fgcolor CDATA #IMPLIED >
<!ATTLIST object_ellipse bgcolor CDATA #IMPLIED >
<!ATTLIST object_ellipse layer CDATA #IMPLIED >
<!ATTLIST object_ellipse transparency (true|false) #IMPLIED >

<!ELEMENT object_extern (#PCDATA) >
<!ATTLIST object_extern class CDATA #REQUIRED >
<!ATTLIST object_extern constructor CDATA #REQUIRED >

<!ELEMENT programs (program+) >

<!ELEMENT program (visible|label|setxy|setx|sety|moveto|wait|sleep|state|goto|trigger|up|down|left|right|angle|click|setproperty|blink|stop)+ >
<!ATTLIST program assigned_to CDATA #REQUIRED >

<!ELEMENT click EMPTY >

<!ELEMENT visible EMPTY >
<!ATTLIST visible value CDATA #REQUIRED >

<!ELEMENT label EMPTY >
<!ATTLIST label value CDATA #REQUIRED >

<!ELEMENT setxy EMPTY >
<!ATTLIST setxy x CDATA #REQUIRED >
<!ATTLIST setxy y CDATA #REQUIRED >

<!ELEMENT setx EMPTY >
<!ATTLIST setx x CDATA #REQUIRED >

<!ELEMENT sety EMPTY >
<!ATTLIST sety y CDATA #REQUIRED >

<!ELEMENT moveto EMPTY >
<!ATTLIST moveto x CDATA #REQUIRED >
<!ATTLIST moveto y CDATA #REQUIRED >
<!ATTLIST moveto dx CDATA #REQUIRED >
<!ATTLIST moveto dy CDATA #REQUIRED >
<!ATTLIST moveto delay CDATA #REQUIRED >

<!ELEMENT wait EMPTY >
<!ATTLIST wait value CDATA #REQUIRED >

<!ELEMENT sleep EMPTY >
<!ATTLIST sleep value CDATA #REQUIRED >

<!ELEMENT state EMPTY >
<!ATTLIST state value CDATA #REQUIRED >

<!ELEMENT trigger EMPTY >
<!ATTLIST trigger object CDATA #REQUIRED >
<!ATTLIST trigger value CDATA #REQUIRED >

<!ELEMENT goto EMPTY >
<!ATTLIST goto value CDATA #REQUIRED >

<!ELEMENT up EMPTY >
<!ATTLIST up y CDATA #REQUIRED >
<!ATTLIST up dy CDATA #REQUIRED >

<!ELEMENT down EMPTY >
<!ATTLIST down y CDATA #REQUIRED >
<!ATTLIST down dy CDATA #REQUIRED >

<!ELEMENT left EMPTY >
<!ATTLIST left x CDATA #REQUIRED >
<!ATTLIST left dx CDATA #REQUIRED >

<!ELEMENT right EMPTY >
<!ATTLIST right x CDATA #REQUIRED >
<!ATTLIST right dx CDATA #REQUIRED >

<!ELEMENT angle EMPTY >
<!ATTLIST angle degrees CDATA #REQUIRED >

<!ELEMENT setproperty EMPTY >
<!ATTLIST setproperty object CDATA #REQUIRED >
<!ATTLIST setproperty property CDATA #REQUIRED >
<!ATTLIST setproperty value CDATA #REQUIRED >

<!ELEMENT blink EMPTY >
<!ATTLIST blink times CDATA #REQUIRED >
<!ATTLIST blink delay CDATA #REQUIRED >

<!ELEMENT stop EMPTY >

=== Smitaty/FrameworkAnimationJS/VersionJava/animation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animation SYSTEM "animation.dtd">
<animation>
  <background>../galaxie1.jpg</background>

  <objects>
  
    <object_text 	text="i=1;" 
                 	font="Courier,12,bold"
                 	transparency="true"
                 	fgcolor="125,90,250"
                 	bgcolor="250,245,250">Instruction1</object_text>
                 	
    <object_text 	text="i=2;" 
    				font="Courier,14,plain"
    				fgcolor="210,70,89">Instruction2</object_text>
    				
    <object_text 	text="i=3;" 
    				font="Courier,16,plain"
    				fgcolor="70,210,89">Instruction3</object_text>
    		
    <object_image   image="../spaceship.png">Image1</object_image>
    		
    <object_rectangle width="100" 
    				height="50"
    				bgcolor="160,160,180"
    				fgcolor="0,80,0">Box1</object_rectangle>
    				
  </objects>
  
 

  <programs>
    <program assigned_to="Instruction1">
      <visible value="true" />
      <label value="loop1" />
      <setxy x="100" y="100" />
      <moveto x="200" y="100" dx="5" dy="0" delay="1" />
      <moveto x="200" y="200" dx="0" dy="5" delay="1" />
      <wait value="step1" />
      <state value="step0" />
      <moveto x="100" y="200" dx="-10" dy="0" delay="1" />
      <moveto x="100" y="100" dx="0" dy="-10" delay="1" />
      <trigger object="Instruction2" value="step1" />
      <goto value="loop1" />
    </program>

    <program assigned_to="Instruction2">
      <visible value="true" />
      <label value="loop1" />
      <setxy x="10" y="10" />
      <angle degrees="45" />
      <moveto x="400" y="400" dx="5" dy="5" delay="4" />
      <trigger object="Instruction1" value="step1" />
      <angle degrees="90" />
      <moveto x="10" y="10" dx="-10" dy="-10" delay="2" />
      <trigger object="Instruction1" value="step1" />
      <wait value="step1" />
      <state value="step0" />
      <goto value="loop1" />
    </program>

	<program assigned_to="Instruction3">
      <visible value="true" />
      <label value="loop1" />
      <setxy x="100" y="100" />
      <right x="100" dx="5" />
      <down y="100" dy="5" />
      <left x="100" dx="5" />
      <up y="100" dy="5" />
      <goto value="loop1" />
    </program>
    
	<program assigned_to="Image1">
      <visible value="true" />
      <label value="loop1" />
      <setxy x="400" y="200" />
      <right x="100" dx="5" />
      <down y="100" dy="5" />
      <left x="100" dx="5" />
      <up y="100" dy="5" />
      <goto value="loop1" />
      </program>
      
      <program assigned_to="Box1">
      <visible value="true" />
      <label value="loop1" />
      <setxy x="100" y="300" />
      <right x="100" dx="1" />
      <down y="100" dy="1" />
      <left x="100" dx="1" />
      <up y="100" dy="1" />
      <goto value="loop1" />
      </program>
      
  </programs>
</animation>

=== Smitaty/FrameworkAnimationJS/VersionJS/cpu_mono_core.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animation SYSTEM "animation.dtd">
<animation>
  <init>
    <start_button present="false" />
  </init>

  <background>img/cpu_mono_core.png</background>

  <objects>
    <object_text
      text="Press on i1 to start"
      font="Courier,12,bold"
      color="0,0,0"
      padding="2"
      background_transparent="true">Message</object_text>

    <object_text
      text="i1"
      font="Courier,12,bold"
      background_color="255,127,0"
      color="0,0,0"
      padding="2"
      background_transparent="false">I1</object_text>

    <object_text
      text="i2"
      font="Courier,12,bold"
      background_color="255,127,0"
      color="0,0,0"
      padding="2"
      background_transparent="false">I2</object_text>

    <object_text
      text="i3"
      font="Courier,12,bold"
      background_color="255,127,0"
      color="0,0,0"
      padding="2"
      background_transparent="false">I3</object_text>

    <object_text
      text="i4"
      font="Courier,12,bold"
      background_color="255,127,0"
      color="0,0,0"
      padding="2"
      background_transparent="false">I4</object_text>

    <object_text
      text="j1"
      font="Courier,12,bold"
      background_color="0,102,204"
      color="255,255,255"
      padding="2"
      background_transparent="false">J1</object_text>

    <object_text
      text="j2"
      font="Courier,12,bold"
      background_color="0,102,204"
      color="255,255,255"
      padding="2"
      background_transparent="false">J2</object_text>

    <object_text
      text="j3"
      font="Courier,12,bold"
      background_color="0,102,204"
      color="255,255,255"
      padding="2"
      background_transparent="false">J3</object_text>

    <object_text
      text="j4"
      font="Courier,12,bold"
      background_color="0,102,204"
      color="255,255,255"
      padding="2"
      background_transparent="false">J4</object_text>

  </objects>

  <programs>

    <program assigned_to="Message">
      <setxy x="20" y="20" />
      <visible value="true" />
      <wait value="i1_clicked" />
      <visible value="false" />
    </program>

    <program assigned_to="I1">
      <setxy x="100" y="77" />
      <visible value="true" />
      <click />
      <trigger object="Message" value="i1_clicked" />
      <right x="135" dx="5" />
      <down y="40" dy="1" />
      <trigger object="J1" value="unlock" />
      <right x="375" dx="2" />
    </program>

    <program assigned_to="I2">
      <setxy x="75" y="77" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="160" dx="5" />
      <down y="40" dy="1" />
      <trigger object="J2" value="unlock" />
      <right x="325" dx="2" />
    </program>

    <program assigned_to="I3">
      <setxy x="50" y="77" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="185" dx="5" />
      <down y="40" dy="1" />
      <trigger object="J3" value="unlock" />
      <right x="275" dx="2" />
    </program>

    <program assigned_to="I4">
      <setxy x="25" y="77" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="210" dx="5" />
      <down y="40" dy="1" />
      <trigger object="J4" value="unlock" />
      <right x="225" dx="2" />
    </program>

    <program assigned_to="J1">
      <setxy x="100" y="157" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="135" dx="5" />
      <up y="40" dy="1" />
      <trigger object="I2" value="unlock" />
      <right x="350" dx="2" />
    </program>

    <program assigned_to="J2">
      <setxy x="75" y="157" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="160" dx="5" />
      <up y="40" dy="1" />
      <trigger object="I3" value="unlock" />
      <right x="300" dx="2" />
    </program>

    <program assigned_to="J3">
      <setxy x="50" y="157" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="185" dx="5" />
      <up y="40" dy="1" />
      <trigger object="I4" value="unlock" />
      <right x="250" dx="2" />
    </program>

    <program assigned_to="J4">
      <setxy x="25" y="157" />
      <visible value="true" />
      <wait value="unlock" />
      <right x="210" dx="5" />
      <up y="40" dy="1" />
      <right x="200" dx="2" />
    </program>

  </programs>

</animation>

=== Smitaty/FrameworkAnimationJS/VersionJS/benchmark_instructions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animation SYSTEM "animation.dtd">
<animation
		marker_enabled="false"
		marker_color="255,0,0"
		marker_stroke_weight="5">
	<init>
		<start_button present="false" />
	</init>

	<background>
		#86A8E7
	</background>

	<objects>
		<object_text
				halignment="center"
				valignment="center"
				x="10"
				y="10"
				background_color="209,107,165"
				background_transparent="0"
				border_color="0,0,0"
				border_transparency="1"
				border_size="1"
				font="Courier,14,normal"
				text="center"
				layer="0"
				visible="true"
				opacity="1"
				angle="0"
				width="60"
				height="40"
				round="10,10,10,10">rect_center</object_text>
		<object_text
				halignment="center"
				valignment="center"
				x="75"
				y="10"
				background_color="209,107,165"
				background_transparent="0"
				border_color="0,0,0"
				border_transparency="1"
				border_size="1"
				font="Courier,14,normal"
				text="blink"
				layer="0"
				visible="true"
				opacity="1"
				angle="0"
				width="60"
				height="40"
				round="10,10,10,10">rect_blink</object_text>
		<object_text
				halignment="center"
				valignment="center"
				x="140"
				y="55"
				background_color="209,107,165"
				background_transparent="0"
				border_color="0,0,0"
				border_transparency="1"
				border_size="1"
				font="Courier,14,normal"
				text="centerx"
				layer="0"
				visible="true"
				opacity="1"
				angle="0"
				width="60"
				height="40"
				round="10,10,10,10">rect_centerx</object_text>
		<object_text
				halignment="center"
				valignment="center"
				x="205"
				y="10"
				background_color="209,107,165"
				background_transparent="0"
				border_color="0,0,0"
				border_transparency="1"
				border_size="1"
				font="Courier,14,normal"
				text="centery"
				layer="0"
				visible="true"
				opacity="1"
				angle="0"
				width="60"
				height="40"
				round="10,10,10,10">rect_centery</object_text>
		<object_text
				halignment="center"
				valignment="center"
				x="270"
				y="10"
				background_color="209,107,165"
				background_transparent="0"
				border_color="0,0,0"
				border_transparency="1"
				border_size="1"
				font="Courier,14,normal"
				text="click"
				layer="0"
				visible="true"
				opacity="1"
				angle="0"
				width="60"
				height="40"
				round="10,10,10,10">rect_click</object_text>
		<object_text
				halignment="center"
				valignment="center"
				x="335"
				y="10"
				background_color="209,107,165"
				background_transparent="0"
				border_color="0,0,0"
				border_transparency="1"
				border_size="1"
				font="Courier,14,normal"
				text="down"
				layer="0"
				visible="true"
				opacity="1"
				angle="0"
				width="60"
				height="40"
				round="10,10,10,10">rect_down</object_text>
		<object_text
				halignment="center"
				valignment="center"
				x="400"
				y="10"
				background_color="209,107,165"
				background_transparent="0"
				border_color="0,0,0"
				border_transparency="1"
				border_size="1"
				font="Courier,14,normal"
				text="goto"
				layer="0"
				visible="true"
				opacity="1"
				angle="0"
				width="60"
				height="40"
				round="10,10,10,10">rect_goto</object_text>
		<object_text
				halignment="center"
				valignment="center"
				x="465"
				y="10"
				background_color="209,107,165"
				background_transparent="0"
				border_color="0,0,0"
				border_transparency="1"
				border_size="1"
				font="Courier,14,normal"
				text="label"
				layer="0"
				visible="true"
				opacity="1"
				angle="0"
				width="60"
				height="40"
				round="10,10,10,10">rect_label</object_text>
		<object_text
				halignment="center"
				valignment="center"
				x="530"
				y="55"
				background_color="209,107,165"
				background_transparent="0"
				border_color="0,0,0"
				border_transparency="1"
				border_size="1"
				font="Courier,14,normal"
				text="left"
				layer="0"
				visible="true"
				opacity="1"
				angle="0"
				width="60"
				height="40"
				round="10,10,10,10">rect_left</object_text>
		<object_text
				halignment="center"
				valignment="center"
				x="595"
				y="10"
				background_color="209,107,165"
				background_transparent="0"
				border_color="0,0,0"
				border_transparency="1"
				border_size="1"
				font="Courier,14,normal"
				text="moveto"
				layer="0"
				visible="true"
				opacity="1"
				angle="0"
				width="60"
				height="40"
				round="10,10,10,10">rect_moveto</object_text>
		<object_text
				halignment="center"
				valignment="center"
				x="660"
				y="55"
				background_color="209,107,165"
				background_transparent="0"
				border_color="0,0,0"
				border_transparency="1"
				border_size="1"
				font="Courier,14,normal"
				text="right"
				layer="0"
				visible="true"
				opacity="1"
				angle="0"
				width="60"
				height="40"
				round="10,10,10,10">rect_right</object_text>
		<object_text
				halignment="center"
				valignment="center"
				x="725"
				y="10"
				background_color="209,107,165"
				background_transparent="0"
				border_color="0,0,0"
				border_transparency="1"
				border_size="1"
				font="Courier,14,normal"
				text="sleep"
				layer="0"
				visible="true"
				opacity="1"
				angle="0"
				width="60"
				height="40"
				round="10,10,10,10">rect_sleep</object_text>
		<object_text
				halignment="center"
				valignment="center"
				x="790"
				y="10"
				background_color="209,107,165"
				background_transparent="0"
				border_color="0,0,0"
				border_transparency="1"
				border_size="1"
				font="Courier,14,normal"
				text="state"
				layer="0"
				visible="true"
				opacity="1"
				angle="0"
				width="60"
				height="40"
				round="10,10,10,10">rect_state</object_text>
		<object_text
				halignment="center"
				valignment="center"
				x="855"
				y="10"
				background_color="209,107,165"
				background_transparent="0"
				border_color="0,0,0"
				border_transparency="1"
				border_size="1"
				font="Courier,14,normal"
				text="stop"
				layer="0"
				visible="true"
				opacity="1"
				angle="0"
				width="60"
				height="40"
				round="10,10,10,10">rect_stop</object_text>
		<object_text
				halignment="center"
				valignment="center"
				x="920"
				y="10"
				background_color="209,107,165"
				background_transparent="0"
				border_color="0,0,0"
				border_transparency="1"
				border_size="1"
				font="Courier,14,normal"
				text="trigger"
				layer="0"
				visible="true"
				opacity="1"
				angle="0"
				width="60"
				height="40"
				round="10,10,10,10">rect_trigger</object_text>
		<object_text
				halignment="center"
				valignment="center"
				x="985"
				y="110"
				background_color="209,107,165"
				background_transparent="0"
				border_color="0,0,0"
				border_transparency="1"
				border_size="1"
				font="Courier,14,normal"
				text="up"
				layer="0"
				visible="true"
				opacity="1"
				angle="0"
				width="60"
				height="40"
				round="10,10,10,10">rect_up</object_text>
		<object_text
				halignment="center"
				valignment="center"
				x="1050"
				y="10"
				background_color="209,107,165"
				background_transparent="0"
				border_color="0,0,0"
				border_transparency="1"
				border_size="1"
				font="Courier,14,normal"
				text="wait"
				layer="0"
				visible="true"
				opacity="1"
				angle="0"
				width="60"
				height="40"
				round="10,10,10,10">rect_wait</object_text>
	</objects>

	<programs>
		<program assigned_to="rect_center">
			<click />
			<center />
		</program>
		<program assigned_to="rect_blink">
			<click />
			<blink
					times="6"
					delay="20" />
		</program>
		<program assigned_to="rect_centerx">
			<click />
			<centerx />
		</program>
		<program assigned_to="rect_centery">
			<click />
			<centery />
		</program>
		<program assigned_to="rect_click">
			<click />
			<setproperty
					object="rect_click"
					property="text"
					value="clicked" />
		</program>
		<program assigned_to="rect_down">
			<click />
			<down
					y="100"
					dy="1" />
		</program>
		<program assigned_to="rect_goto">
			<click />
			<setproperty
					object="rect_goto"
					property="text"
					value="Test@label" />
		</program>
		<program assigned_to="rect_label">
			<click />
			<label value="label" />
			<down
					y="200"
					dy="10" />
			<up
					y="200"
					dy="10" />
			<goto value="label" />
			<trigger
					object="rect_goto"
					value="goto" />
		</program>
		<program assigned_to="rect_left">
			<click />
			<left
					x="100"
					dx="10" />
		</program>
		<program assigned_to="rect_moveto">
			<click />
			<moveto
					x="100"
					y="100"
					dx="5"
					dy="5" />
		</program>
		<program assigned_to="rect_right">
			<click />
			<right
					x="100"
					dx="5" />
		</program>
		<program assigned_to="rect_sleep">
			<click />
			<down
					y="200"
					dy="10" />
			<setproperty
					object="rect_sleep"
					property="text"
					value="Sleep 2s" />
			<sleep value="2000" />
			<setproperty
					object="rect_sleep"
					property="text"
					value="End" />
		</program>
		<program assigned_to="rect_state">
			<click />
			<setproperty
					object="rect_state"
					property="text"
					value="Déprécié" />
		</program>
		<program assigned_to="rect_stop">
			<click />
			<stop />
		</program>
		<program assigned_to="rect_trigger">
			<click />
			<trigger
					object="rect_wait"
					value="trigger" />
		</program>
		<program assigned_to="rect_up">
			<click />
			<up y="100" dy="1" />
		</program>
		<program assigned_to="rect_wait">
			<click />
			<setproperty
					object="rect_wait"
					property="text"
					value="Attend@trigger" />
			<wait value="trigger" />
			<setproperty
					object="rect_wait"
					property="text"
					value="Trigger@recu" />
		</program>
	</programs>

</animation>

=== Smitaty/FrameworkAnimationJS/VersionJava/cpuprog1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animation SYSTEM "animation.dtd">
<animation>

  <init>
  	<start_button text="Click" x="10" y="100" present="false" /> 
  </init>
  
  <background>../cpu8086simple.png</background>
  
  <objects>
  
  <object_ellipse
  	bgcolor="128,0,0"
  	fgcolor="0,128,0"
  	width="50"
  	height="80"
  	transparency="false">Ellipse</object_ellipse>
  	
 
    <object_text 	text="i=1;@i=2;" 
    				layer="1" transparency="false"
                 	font="Courier,12,bold"
                 	bocolor="0,128,0" border="10"
                 	fgcolor="125,90,250"
                 	bgcolor="250,245,250">Instruction1</object_text>
    
    <object_text 	text="i=2;"
    				layer="2"  transparency="false"
                 	font="Courier,12,bold"
                 	fgcolor="125,90,250"
                 	bgcolor="250,245,250">Instruction2</object_text>
      
      
    <object_polygon
      coord_x="10,10,0,15,30,20,20,10"
      coord_y=" 0,10,10,20,10,10,0,0"
      fgcolor="128,0,0"
      bgcolor="0,128,0"
      >Polygone</object_polygon>
      
      <object_image   
      	image="../spaceship.png"
      	width="40"
      	height="40">Image1</object_image>
                   	
      <object_circle
      	fgcolor="128,60,200"
      	bgcolor="200,128,60"
      	rayon="50">Cercle</object_circle>  
      	           	
  </objects>
  
  <programs>
 
 	<program assigned_to="Instruction1">
 		<setxy x="100" y="100" />
 		<visible value="true" />
 		<click />
 		<setproperty object="Instruction2" property="fgcolor" value="255,0,0" />
 		<down y="100" dy="1" />
 	</program>
 	
 	<program assigned_to="Instruction2">
 		<setxy x="150" y="120"/>
 		<visible value="true" />
 		<click />
 		<stop />
 	</program>
 	
 	<program assigned_to="Polygone">
 		<setxy x="250" y="320"/>
 		<visible value="true" />
		<click />
		<up y="100" dy="1" />
 	</program>
 	
 	<program assigned_to="Image1">
 	  <setxy x="400" y="200" />
      <visible value="true" />
      <click />
      <right x="100" dx="5" />
      <down y="100" dy="5" />
      <left x="100" dx="5" />
      <up y="100" dy="5" /> 
    </program>
      
    <program assigned_to="Cercle">
      <setxy x="250" y="100" />
      <visible value="true" />
    <click />
      <right x="100" dx="5" />
    </program>
      
    
    
     <program assigned_to="Ellipse">
      <setxy x="50" y="100" />
      <visible value="true" />
      <click />
      <right x="100" dx="5" />
    </program>
    
  </programs>
  
 </animation>

=== Smitaty/FrameworkAnimationJS/VersionJS/exemple_animation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animation SYSTEM "animation.dtd">
<animation>
  <background>img/galaxie1.jpg</background>

  <objects>

    <object_text
      text="click this text@to start"
      font="Courier,12,bold"
      background_transparent="false"
      background_color="255,255,255"
      color="0,0,0"
      border_color="0,0,128"
      layer="1">Texte</object_text>

    <object_image
      image="img/spaceship.png"
      width="40"
      height="40"
    >Image</object_image>

    <object_polygon
      coord_x="10,10,0,15,30,20,20,10"
      coord_y=" 0,10,10,20,10,10,0,0"
      border_color="255,0,0"
      background_color="0,128,0"
      background_transparent="false"
      border_transparency="false"
      visible="false"
    >Polygone</object_polygon>

  </objects>

  <programs>

    <program assigned_to="Texte">
      <setxy x="10" y="10" />
      <visible value="true" />
      <click />
      <trigger object="Image" value="appear" />
      <setproperty object="Texte" property="text"
        value="Now click on ship@to make it move" />
      <wait value="ship_displayed" />
      <trigger object="Polygone" value="appear" />
      <setproperty object="Texte" property="background_color" value="250,0,0" />
      <setproperty object="Texte" property="text"
        value="Now click on arrow@to make it move" />
      <wait value="arrow_displayed" />
      <setproperty object="Texte" property="background_color" value="0,240,0" />
      <setproperty object="Texte" property="text"
        value="Now click here@to stop animation" />
      <click />
      <stop />
    </program>

    <program assigned_to="Image">
      <wait value="appear" />
      <setxy x="100" y="100" />
      <visible value="true" />
      <click />
      <trigger object="Texte" value="ship_displayed" />
      <label value="loop" />
      <moveto x="200" y="200" dx="1" dy="1" delay="2" />
      <moveto x="100" y="100" dx="5" dy="5" delay="2" />
      <goto value="loop" />
    </program>

    <program assigned_to="Polygone">
      <wait value="appear" />
      <setxy x="300" y="100" />
      <visible value="true" />
      <click />
      <trigger object="Texte" value="arrow_displayed" />
      <label value="loop" />
      <right x="100" dx="5" />
      <down y="100" dy="5" />
      <left x="100" dx="5" />
      <up y="100" dy="5" />
      <goto value="loop" />
    </program>

  </programs>

</animation>
